
import type { StartupListing } from '../types';

const dummyData: StartupListing[] = [
  {
    id: '1',
    name: 'CodeStream',
    tagline: 'AI-powered pair programming in your IDE.',
    category: 'Developer Tools',
    description: 'CodeStream enhances developer productivity by providing an AI assistant that can review code, suggest improvements, and answer technical questions directly within the development environment. It supports over 20 languages and integrates with popular IDEs like VS Code and JetBrains.',
    problem: 'Developers spend too much time on code reviews and debugging simple issues, which slows down the development cycle.',
    solution: 'An AI pair programmer that provides real-time feedback and assistance, catching bugs before they make it to production and improving code quality.',
    targetAudience: 'Software development teams in startups and large enterprises.',
    businessType: 'B2B',
    projectUrl: 'https://codestream.dev',
    twitterUrl: 'https://x.com/codestream',
    paymentGatewayApiKey: 'pk_test_dummy_codestream',
    techStack: ['TypeScript', 'Python', 'AWS', 'Docker', 'Kubernetes'],
    mrr: 15000,
    mrrVerified: true,
    users: 2500,
    usersVerified: true,
    price: 450000,
    lifetimeRevenue: 850000,
    whatYouGet: ['Domain', 'Source Code', 'Customer List', 'Social Media Accounts'],
    founder: {
      name: 'Jane Doe',
      bio: 'Ex-Google software engineer with a passion for developer productivity tools.',
      founderTwitterUrl: 'https://x.com/janedoe_dev'
    },
    qna: [
      { question: 'What is your unique competitive advantage?', answer: 'Our AI model is fine-tuned specifically for code quality and performance, offering more accurate suggestions than general-purpose models. Deep IDE integration is also a key differentiator.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'Content marketing through a technical blog, targeted ads on developer forums, and a freemium model that encourages team adoption.' },
      { question: 'Why are you selling this business?', answer: 'I am moving on to a new venture in the quantum computing space and want to find a passionate team to take CodeStream to the next level.' },
    ],
  },
  {
    id: '2',
    name: 'Healthica',
    tagline: 'Personalized meal planning powered by AI.',
    category: 'HealthTech',
    description: 'Healthica is a mobile app that creates personalized weekly meal plans based on user\'s dietary restrictions, fitness goals, and taste preferences. Our AI algorithm analyzes nutritional data and user feedback to optimize plans over time.',
    problem: 'People struggle to maintain healthy diets due to the complexity and time commitment of meal planning.',
    solution: 'An automated, intelligent meal planner that removes the guesswork from healthy eating, providing recipes and grocery lists.',
    targetAudience: 'Health-conscious individuals, fitness enthusiasts, and people with dietary restrictions.',
    businessType: 'B2C',
    projectUrl: 'https://healthica.app',
    twitterUrl: 'https://x.com/healthica',
    paymentGatewayApiKey: 'pk_test_dummy_healthica',
    techStack: ['React Native', 'Node.js', 'PostgreSQL', 'Heroku'],
    mrr: 8500,
    mrrVerified: true,
    users: 12000,
    usersVerified: false,
    price: 250000,
    lifetimeRevenue: 420000,
    whatYouGet: ['Mobile App (iOS & Android)', 'Source Code', 'User Database', 'Brand Assets'],
    founder: {
      name: 'Mike Redding',
      bio: 'Nutritionist and full-stack developer dedicated to making healthy living accessible to everyone.',
      founderTwitterUrl: 'https://x.com/mikeredding'
    },
    qna: [
      { question: 'What is your unique competitive advantage?', answer: 'Our personalization algorithm is more advanced than competitors, leading to higher user retention. We also have a strong community aspect within the app.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'Partnerships with fitness influencers, social media advertising on Instagram and Pinterest, and App Store Optimization (ASO).' },
      { question: 'Why are you selling this business?', answer: 'I\'ve received a research grant to study dietary patterns and will not have the time to manage the business operations.' },
    ],
  },
  {
    id: '3',
    name: 'FinScribe',
    tagline: 'Automated bookkeeping for freelancers.',
    category: 'Fintech',
    description: 'FinScribe is a SaaS platform that connects to a freelancer\'s bank accounts and automatically categorizes expenses, tracks income, and generates reports for tax season. It simplifies financial management for the self-employed.',
    problem: 'Freelancers and sole proprietors find bookkeeping tedious, time-consuming, and error-prone.',
    solution: 'A simple, automated system that handles 90% of bookkeeping tasks, saving users hours each month and ensuring tax readiness.',
    targetAudience: 'Freelancers, consultants, and independent contractors.',
    businessType: 'B2B',
    projectUrl: 'https://finscribe.io',
    twitterUrl: 'https://x.com/finscribe',
    paymentGatewayApiKey: 'pk_test_dummy_finscribe',
    techStack: ['Vue.js', 'Go', 'Stripe Connect', 'Plaid API', 'GCP'],
    mrr: 22000,
    mrrVerified: true,
    users: 4000,
    usersVerified: true,
    price: 750000,
    lifetimeRevenue: 1200000,
    whatYouGet: ['Web Application', 'Source Code', 'Stripe & Plaid integrations', 'Customer list'],
    founder: {
      name: 'Sarah Chen',
      bio: 'A former CPA who saw a gap in the market for simple financial tools for the gig economy.',
      founderTwitterUrl: 'https://x.com/sarahchencpa'
    },
    qna: [
      { question: 'What is your unique competitive advantage?', answer: 'Our focus on extreme simplicity and automation for a niche market (freelancers) sets us apart from more complex accounting software.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'SEO for freelance finance keywords, partnerships with co-working spaces, and a referral program.' },
      { question: 'Why are you selling this business?', answer: 'I\'m looking to retire and travel. The business is profitable and stable, perfect for a new owner to grow.' },
    ],
  },
  {
    id: '4',
    name: 'CreatorKit',
    tagline: 'The all-in-one platform for content creators.',
    category: 'Creator Economy',
    description: 'CreatorKit provides tools for creators to manage their audience, monetize content, and analyze their growth. It includes features like paid newsletters, digital product sales, and community management.',
    problem: 'Creators have to stitch together multiple tools for newsletters, payments, and community, which is inefficient and expensive.',
    solution: 'A single, integrated platform that provides all the core tools a creator needs to build and monetize their audience.',
    targetAudience: 'YouTubers, bloggers, podcasters, and newsletter writers.',
    businessType: 'B2C',
    projectUrl: 'https://creatorkit.com',
    twitterUrl: 'https://x.com/creatorkit',
    paymentGatewayApiKey: 'pk_test_dummy_creatorkit',
    techStack: ['Next.js', 'Supabase', 'TailwindCSS', 'Vercel'],
    mrr: 12000,
    mrrVerified: false,
    users: 1800,
    usersVerified: true,
    price: 380000,
    lifetimeRevenue: 650000,
    whatYouGet: ['SaaS Platform', 'Source Code', 'Brand Assets', 'Community Forum'],
    founder: {
      name: 'Alex Martinez',
      bio: 'A former content creator who built the tools he always wished he had.',
      founderTwitterUrl: 'https://x.com/alexcreates'
    },
    qna: [
      { question: 'What is your unique competitive advantage?', answer: 'We are laser-focused on the creator workflow and offer a superior user experience compared to larger, more generic platforms.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'Building in public on Twitter, sponsoring creator-focused newsletters, and affiliate marketing with established creators.' },
      { question: 'Why are you selling this business?', answer: 'A larger company in the creator space has acquired a different project of mine, and I have a conflict of interest.' },
    ],
  },
  {
    id: '5',
    name: 'EcoCart',
    tagline: 'Sustainable products marketplace.',
    category: 'GreenTech',
    description: 'EcoCart is an e-commerce platform that exclusively features products from vetted, environmentally-friendly brands. We focus on transparency, providing a "sustainability score" for each product.',
    problem: 'Consumers want to shop sustainably but find it difficult to identify and trust truly eco-friendly brands.',
    solution: 'A curated, trusted marketplace that makes sustainable shopping easy and transparent.',
    targetAudience: 'Eco-conscious consumers.',
    businessType: 'B2C',
    projectUrl: 'https://ecocart.com',
    twitterUrl: 'https://x.com/ecocart',
    paymentGatewayApiKey: 'pk_test_dummy_ecocart',
    techStack: ['Shopify Plus', 'Hydrogen', 'Sanity CMS'],
    mrr: 35000,
    mrrVerified: true,
    users: 50000,
    usersVerified: true,
    price: 900000,
    lifetimeRevenue: 2100000,
    whatYouGet: ['E-commerce Store', 'Supplier Relationships', 'Brand', 'Social Media Following'],
    founder: {
        name: 'Emily Carter',
        bio: 'Environmental scientist turned entrepreneur on a mission to promote conscious consumerism.',
        founderTwitterUrl: 'https://x.com/emilycartereco'
    },
    qna: [
        { question: 'What is your unique competitive advantage?', answer: 'Our rigorous vetting process and transparent sustainability scoring system builds a high level of trust with consumers that generic marketplaces like Amazon lack.' },
        { question: 'What is your primary customer acquisition strategy?', answer: 'SEO for sustainable product keywords, partnerships with environmental blogs and publications, and a strong presence on Pinterest.' },
        { question: 'Why are you selling this business?', answer: 'I am taking on a leadership role at a non-profit focused on reforestation and can no longer dedicate the required time to EcoCart.' },
    ],
  },
  {
    id: '6',
    name: 'PixelPulse',
    tagline: 'Analytics for Indie Game Developers.',
    category: 'Gaming',
    description: 'A SaaS tool that integrates with Steam, Itch.io, and mobile stores to provide indie developers with actionable insights on player engagement, retention, and monetization.',
    problem: 'Indie game developers lack the resources for complex data analysis, making it hard to understand player behavior and improve their games.',
    solution: 'An affordable, easy-to-use analytics platform with pre-built dashboards and reports tailored for game developers.',
    targetAudience: 'Independent game developers and small game studios.',
    businessType: 'B2B',
    projectUrl: 'https://pixelpulse.gg',
    twitterUrl: 'https://x.com/pixelpulse',
    paymentGatewayApiKey: 'pk_test_dummy_pixelpulse',
    techStack: ['React', 'Python (Flask)', 'ClickHouse', 'AWS'],
    mrr: 7000,
    mrrVerified: true,
    users: 600,
    usersVerified: true,
    price: 210000,
    lifetimeRevenue: 380000,
    whatYouGet: ['SaaS Platform', 'Source Code', 'API integrations', 'Developer community access'],
    founder: {
        name: 'Ben "Woz" Wozniak',
        bio: 'A lifelong gamer and data scientist who wanted to give indie devs the same tools as AAA studios.',
        founderTwitterUrl: 'https://x.com/woz'
    },
    qna: [
        { question: 'What is your unique competitive advantage?', answer: 'We are hyper-focused on the needs of indie developers, offering specific metrics and integrations that larger, more generic analytics companies ignore.' },
        { question: 'What is your primary customer acquisition strategy?', answer: 'Sponsoring game jams, maintaining an active presence on indie developer forums, and creating valuable content on game design and marketing.' },
        { question: 'Why are you selling this business?', answer: 'My own game project has unexpectedly taken off, and I want to focus my energy on developing it full-time.' },
    ],
  },
  {
    id: '7',
    name: 'StudySync',
    tagline: 'Collaborative learning tools for university students.',
    category: 'EdTech',
    description: 'StudySync is a web platform where students can form virtual study groups, share notes with real-time collaboration, and create flashcards. It uses spaced repetition algorithms to optimize learning.',
    problem: 'Remote and hybrid learning has made it difficult for students to collaborate effectively and stay motivated.',
    solution: 'A suite of digital tools that replicates the benefits of in-person study groups in an online environment, enhanced with learning science.',
    targetAudience: 'University and college students.',
    businessType: 'B2C',
    projectUrl: 'https://studysync.co',
    twitterUrl: 'https://x.com/studysync',
    paymentGatewayApiKey: 'pk_test_dummy_studysync',
    techStack: ['Laravel', 'Livewire', 'Alpine.js', 'DigitalOcean'],
    mrr: 5000,
    mrrVerified: false,
    users: 30000,
    usersVerified: true,
    price: 150000,
    lifetimeRevenue: 280000,
    whatYouGet: ['Web Application', 'Source Code', 'Userbase', 'Educational Content'],
    founder: {
        name: 'Aisha Khan',
        bio: 'A recent graduate who started StudySync to solve the problems she faced while studying during the pandemic.',
        founderTwitterUrl: 'https://x.com/aishakhan'
    },
    qna: [
        { question: 'What is your unique competitive advantage?', answer: 'Our real-time collaboration feature for note-taking is best-in-class, and our focus on a simple, intuitive UI has led to strong word-of-mouth growth.' },
        { question: 'What is your primary customer acquisition strategy?', answer: 'A campus ambassador program, targeted social media ads at the beginning of each semester, and organic growth through study group invites.' },
        { question: 'Why are you selling this business?', answer: 'I\'m starting a PhD program and want the platform to continue thriving under new ownership.' },
    ],
  },
  {
    id: '8',
    name: 'DataWeave',
    tagline: 'Archiving digital data in synthetic DNA.',
    category: 'BioTech',
    description: 'DataWeave is a deep-tech startup that has pioneered a method for encoding digital data into synthetic DNA molecules, offering an incredibly dense and long-lasting storage solution.',
    problem: 'Current data storage methods (tape, hard drives) degrade over time and require massive, energy-intensive data centers.',
    solution: 'A new paradigm for archival storage that is thousands of times denser than flash memory and can last for centuries with zero energy consumption.',
    targetAudience: 'Large corporations, government archives, and research institutions with massive long-term data storage needs.',
    businessType: 'B2B',
    projectUrl: 'https://dataweave.bio',
    twitterUrl: 'https://x.com/dataweave',
    paymentGatewayApiKey: 'pk_test_dummy_dataweave',
    techStack: ['Python', 'BioPython', 'FPGA', 'Custom Synthesis Hardware'],
    mrr: 2000,
    mrrVerified: true,
    users: 10,
    usersVerified: true,
    price: 5000000,
    lifetimeRevenue: 15000000,
    whatYouGet: ['Patented Encoding/Decoding Process', 'Lab Equipment', 'Source Code for algorithms', 'Existing research contracts'],
    founder: {
      name: 'Dr. Alani Vance',
      bio: 'PhD in synthetic biology with over 15 years of research experience in DNA-based technologies.',
      founderTwitterUrl: 'https://x.com/alanivance'
    },
    qna: [
      { question: 'What is the current state of the technology?', answer: 'We have a working prototype that can encode and decode small files (megabytes) with 100% accuracy. The primary challenge is scaling up the synthesis process to be cost-effective.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'Direct outreach to CTOs and Heads of R&D at Fortune 500 companies, as well as securing government research grants.' },
      { question: 'Why are you selling this business?', answer: 'We are looking for a strategic acquisition by a larger tech or biotech company that has the resources to scale the hardware manufacturing.' },
    ],
  },
  {
    id: '9',
    name: 'RemoteFlow',
    tagline: 'The asynchronous OS for remote teams.',
    category: 'SaaS',
    description: 'RemoteFlow is a project management tool designed specifically for asynchronous communication. It replaces daily stand-ups with check-ins, tracks progress across timezones, and integrates with Slack and GitHub.',
    problem: 'Traditional project management tools are built for synchronous, in-office work, leading to meeting fatigue and communication bottlenecks in remote teams.',
    solution: 'A platform that structures communication and workflows around asynchronous principles, improving deep work and team autonomy.',
    targetAudience: 'Fully remote startups and distributed teams.',
    businessType: 'B2B',
    projectUrl: 'https://remoteflow.com',
    twitterUrl: 'https://x.com/remoteflow',
    paymentGatewayApiKey: 'pk_test_dummy_remoteflow',
    techStack: ['Ruby on Rails', 'StimulusReflex', 'PostgreSQL', 'Heroku'],
    mrr: 18000,
    mrrVerified: true,
    users: 350,
    usersVerified: true,
    price: 650000,
    lifetimeRevenue: 1100000,
    whatYouGet: ['SaaS Platform', 'Source Code', 'Customer list', 'Content marketing blog'],
    founder: {
      name: 'Liam Gallagher',
      bio: 'Has been leading remote teams for over a decade and built RemoteFlow to solve his own frustrations.',
      founderTwitterUrl: 'https://x.com/liamg'
    },
    qna: [
      { question: 'How do you differ from giants like Asana or Jira?', answer: 'We are intentionally simpler and more opinionated. We don\'t try to be everything for everyone. Our entire UX is built around async work, which makes us a better fit for teams that have fully embraced it.' },
      { question: 'What is your churn rate?', answer: 'Our net revenue churn is negative, as existing teams tend to add more seats over time. Gross MRR churn is around 4% monthly.' },
      { question: 'Why are you selling this business?', answer: 'I\'m experiencing burnout from being a solo founder and would like to join a larger company in a product leadership role.' },
    ],
  },
   {
    id: '10',
    name: 'PetPlate Custom',
    tagline: 'Personalized, vet-designed meal plans for your dog.',
    category: 'E-commerce',
    description: 'A D2C subscription service that delivers freshly made, human-grade dog food tailored to a dog\'s specific needs (age, breed, activity level, allergies).',
    problem: 'Mass-produced kibble is often filled with low-quality ingredients and doesn\'t address the unique dietary needs of individual dogs.',
    solution: 'A convenient subscription service for healthy, customized pet food, making it easy for owners to provide the best nutrition for their dogs.',
    targetAudience: 'Dog owners who view their pets as family and are willing to spend a premium on their health and wellness.',
    businessType: 'B2C',
    projectUrl: 'https://petplatecustom.com',
    twitterUrl: 'https://x.com/petplatecustom',
    paymentGatewayApiKey: 'pk_test_dummy_petplate',
    techStack: ['Shopify Plus', 'Recharge', 'Custom Subscription Portal (React)'],
    mrr: 45000,
    mrrVerified: true,
    users: 1500,
    usersVerified: true,
    price: 1200000,
    lifetimeRevenue: 3500000,
    whatYouGet: ['E-commerce store', 'Subscriber list', 'Supplier contracts', 'Brand & social media accounts'],
    founder: {
      name: 'Dr. Chloe Davis',
      bio: 'A veterinarian who became passionate about pet nutrition after seeing the impact of diet on her patients\' health.',
      founderTwitterUrl: 'https://x.com/drchloedavis'
    },
    qna: [
      { question: 'What are your customer acquisition costs (CAC) and lifetime value (LTV)?', answer: 'Our CAC is around $80, primarily through Facebook/Instagram ads. Our LTV is over $500, with an average subscription length of 14 months.' },
      { question: 'How do you handle logistics and shipping?', answer: 'We partner with a commercial kitchen and a third-party logistics (3PL) provider that specializes in cold-chain shipping to ensure freshness.' },
      { question: 'Why are you selling this business?', answer: 'I\'m looking to focus on the clinical side of my veterinary practice and want a seasoned e-commerce operator to take over and scale the business.' },
    ],
  },
  {
    id: '11',
    name: 'LexiScan',
    tagline: 'AI-powered contract analysis for legal professionals.',
    category: 'AI',
    description: 'LexiScan is a SaaS tool that uses natural language processing to scan legal documents (like NDAs, MSAs) and identify key clauses, potential risks, and non-standard language in seconds.',
    problem: 'Lawyers and paralegals spend countless hours manually reviewing tedious legal documents, a process that is both expensive and prone to human error.',
    solution: 'An AI assistant that dramatically speeds up the contract review process, reduces risk, and frees up legal professionals to focus on higher-value tasks.',
    targetAudience: 'Solo attorneys, small law firms, and in-house legal departments.',
    businessType: 'B2B',
    projectUrl: 'https://lexiscan.ai',
    twitterUrl: 'https://x.com/lexiscan',
    paymentGatewayApiKey: 'pk_test_dummy_lexiscan',
    techStack: ['Python (Django)', 'React', 'spaCy', 'Hugging Face Transformers', 'AWS'],
    mrr: 9000,
    mrrVerified: true,
    users: 400,
    usersVerified: true,
    price: 350000,
    lifetimeRevenue: 720000,
    whatYouGet: ['SaaS platform', 'Proprietary fine-tuned AI models', 'Source code', 'Customer data'],
    founder: {
      name: 'Rohan Gupta',
      bio: 'A corporate lawyer who taught himself to code to build the tool he always wanted.',
      founderTwitterUrl: 'https://x.com/rohanlegal'
    },
    qna: [
      { question: 'How accurate is the AI model?', answer: 'For standard contract types like NDAs, our model achieves over 95% accuracy in identifying critical clauses. We are constantly improving it with more data.' },
      { question: 'What is your primary customer acquisition strategy?', answer: 'Content marketing via a legal tech blog, webinars for Continuing Legal Education (CLE) credits, and targeted ads on LinkedIn.' },
      { question: 'Why are you selling this business?', answer: 'I want to focus on the AI research aspect and would prefer to sell to a company that can handle the sales and marketing more effectively.' },
    ],
  },
  {
    id: '12',
    name: 'Localist',
    tagline: 'Authentic city guides curated by locals.',
    category: 'Mobile',
    description: 'Localist is a mobile app that offers curated travel guides and experiences created by local artists, chefs, and creatives, offering an alternative to tourist traps.',
    problem: 'Travelers are tired of generic, tourist-focused recommendations and crave authentic, local experiences.',
    solution: 'A marketplace platform where locals can monetize their knowledge by creating and selling unique city guides and tours.',
    targetAudience: 'Millennial and Gen Z travelers looking for authentic cultural experiences.',
    businessType: 'B2C',
    projectUrl: 'https://localist.app',
    twitterUrl: 'https://x.com/localist',
    paymentGatewayApiKey: 'pk_test_dummy_localist',
    techStack: ['Flutter', 'Firebase', 'Google Maps API'],
    mrr: 4000,
    mrrVerified: false,
    users: 50000,
    usersVerified: true,
    price: 120000,
    lifetimeRevenue: 210000,
    whatYouGet: ['iOS & Android Apps', 'Source code', 'User database', 'Creator network'],
    founder: {
      name: 'Sofia Reyes',
      bio: 'A travel blogger and photographer who wanted to create a more authentic way to explore new cities.',
      founderTwitterUrl: 'https://x.com/sofiareyes'
    },
    qna: [
      { question: 'What is your business model?', answer: 'We take a 20% commission on every guide or experience sold through the platform.' },
      { question: 'How do you recruit local curators?', answer: 'Through targeted outreach on Instagram to local creatives and word-of-mouth within the creative communities of our launch cities.' },
      { question: 'Why are you selling this business?', answer: 'I have an opportunity to host a travel show and will not have the time to dedicate to the app\'s growth.' },
    ],
  },
  {
    id: '13',
    name: 'CarbonZero',
    tagline: 'API for calculating and offsetting carbon footprints.',
    category: 'GreenTech',
    description: 'CarbonZero provides a simple API for e-commerce and logistics companies to calculate the carbon footprint of a purchase or shipment and offer customers the option to offset it.',
    problem: 'Companies want to offer sustainability options like carbon offsetting, but the calculation and process are complex to implement.',
    solution: 'A dead-simple API that handles all the complexity of carbon calculation and connects with certified offsetting projects.',
    targetAudience: 'E-commerce platforms, airlines, and logistics companies.',
    businessType: 'B2B',
    projectUrl: 'https://carbonzero.api',
    twitterUrl: 'https://x.com/carbonzero',
    paymentGatewayApiKey: 'pk_test_dummy_carbonzero',
    techStack: ['Node.js', 'Express', 'Stripe', 'PostGIS', 'GCP'],
    mrr: 11000,
    mrrVerified: true,
    users: 80,
    usersVerified: true,
    price: 400000,
    lifetimeRevenue: 950000,
    whatYouGet: ['API Service', 'Source code', 'Client integrations', 'Partnerships with offsetting projects'],
    founder: {
      name: 'Ken Thompson',
      bio: 'Climate scientist turned software engineer.',
      founderTwitterUrl: 'https://x.com/kenthompson'
    },
    qna: [
      { question: 'How do you ensure the quality of the offsetting projects?', answer: 'We partner exclusively with projects that are certified by Gold Standard or Verra, ensuring they are legitimate and effective.' },
      { question: 'What is your pricing model?', answer: 'It\'s a usage-based model. We charge a small fee per API call, plus the direct cost of the carbon offset itself.' },
      { question: 'Why are you selling this business?', answer: 'I am moving to a research-focused role at a university.' },
    ],
  },
  {
    id: '14',
    name: 'StatusPing',
    tagline: 'Simple, beautiful status pages.',
    category: 'Developer Tools',
    description: 'A SaaS that lets companies create a public status page in minutes to communicate downtime and incidents to their customers. No coding required.',
    problem: 'During an outage, engineering teams are busy fixing the problem and don\'t have time to update a status page. Customers are left in the dark.',
    solution: 'An easy-to-use tool that integrates with monitoring services (like Datadog, Pingdom) to automatically update the status page, and allows for quick manual updates.',
    targetAudience: 'SaaS companies of all sizes.',
    businessType: 'B2B',
    projectUrl: 'https://statusping.io',
    twitterUrl: 'https://x.com/statusping',
    paymentGatewayApiKey: 'pk_test_dummy_statusping',
    techStack: ['Elixir', 'Phoenix LiveView', 'PostgreSQL', 'Fly.io'],
    mrr: 16000,
    mrrVerified: true,
    users: 1200,
    usersVerified: true,
    price: 550000,
    lifetimeRevenue: 1300000,
    whatYouGet: ['SaaS Platform', 'Source code', 'Customer list', 'Brand assets'],
    founder: {
      name: 'David Heinemeier Hansson Jr.',
      bio: 'A developer who believes in simplicity and transparency.',
      founderTwitterUrl: 'https://x.com/dhhjr'
    },
    qna: [
      { question: 'How are you different from Atlassian Statuspage?', answer: 'We are much simpler and more affordable. We target startups and SMBs who find Statuspage to be too complex and expensive for their needs.' },
      { question: 'What is your customer acquisition strategy?', answer: 'Primarily inbound through SEO for "status page" related keywords and a very popular free plan that converts to paid plans as companies grow.' },
      { question: 'Why are you selling this business?', answer: 'I\'m a serial entrepreneur and I\'m ready to start my next project. The business is profitable and runs itself for the most part.' },
    ],
  },
   {
    id: '15',
    name: 'SponsorFlow',
    tagline: 'Manage your creator sponsorships in one place.',
    category: 'Creator Economy',
    description: 'SponsorFlow is a CRM for YouTubers and Twitch streamers. It helps them track sponsorship deals, manage contacts, automate outreach, and handle invoicing.',
    problem: 'Full-time creators are running a business, but they lack the tools to manage their sales pipeline for sponsorships effectively.',
    solution: 'A simple, creator-friendly CRM that streamlines the entire sponsorship workflow from initial contact to final payment.',
    targetAudience: 'Professional YouTubers, Twitch streamers, and Instagram influencers.',
    businessType: 'B2B',
    projectUrl: 'https://sponsorflow.app',
    twitterUrl: 'https://x.com/sponsorflow',
    paymentGatewayApiKey: 'pk_test_dummy_sponsorflow',
    techStack: ['Next.js', 'Prisma', 'PlanetScale', 'Vercel'],
    mrr: 6000,
    mrrVerified: true,
    users: 800,
    usersVerified: false,
    price: 180000,
    lifetimeRevenue: 410000,
    whatYouGet: ['SaaS platform', 'Source code', 'User database'],
    founder: {
      name: 'Casey Neistat Jr.',
      bio: 'A former creator manager who saw the need for better business tools for his clients.',
      founderTwitterUrl: 'https://x.com/caseyjr'
    },
    qna: [
      { question: 'What is your primary customer acquisition strategy?', answer: 'We partner with larger creators to promote the tool to their audience (affiliate marketing) and run targeted ads on creator-focused platforms.' },
      { question: 'What are the main reasons for customer churn?', answer: 'The main reason is creators who stop producing content professionally and no longer need the tool.' },
      { question: 'Why are you selling this business?', answer: 'I am joining a venture capital firm that invests in creator economy startups, and I want to avoid any conflict of interest.' },
    ],
  },
  {
    id: '16',
    name: 'PostureUp',
    tagline: 'The smart wearable that corrects your posture.',
    category: 'HealthTech',
    description: 'PostureUp is a small, discreet wearable device that sticks to your upper back and gently vibrates when you start to slouch, reminding you to sit or stand up straight.',
    problem: 'Poor posture from sitting at desks all day leads to chronic back pain, reduced energy, and long-term health issues.',
    solution: 'A simple wearable device and companion app that builds posture awareness through real-time feedback, helping users develop healthier habits.',
    targetAudience: 'Desk workers, students, and anyone concerned about their posture and back health.',
    businessType: 'B2C',
    projectUrl: 'https://postureup.com',
    twitterUrl: 'https://x.com/postureup',
    paymentGatewayApiKey: 'pk_test_dummy_postureup',
    techStack: ['Hardware (BLE)', 'React Native', 'Shopify (for e-commerce)'],
    mrr: 25000,
    mrrVerified: true,
    users: 10000,
    usersVerified: true,
    price: 800000,
    lifetimeRevenue: 2400000,
    whatYouGet: ['Hardware design files', 'Firmware source code', 'Mobile apps', 'E-commerce store', 'Existing inventory'],
    founder: {
      name: 'Dr. Evelyn Reed',
      bio: 'A physical therapist who developed PostureUp to provide her patients with a tool for continuous posture training.',
      founderTwitterUrl: 'https://x.com/drevelynreed'
    },
    qna: [
      { question: 'What are the margins on the hardware?', answer: 'The cost of goods sold (COGS) per unit is approximately $15, and our average selling price is $79, giving us a healthy margin.' },
      { question: 'How do you handle manufacturing and fulfillment?', answer: 'We have a contract manufacturing partner in Shenzhen and use a 3PL in the US for direct-to-consumer fulfillment.' },
      { question: 'Why are you selling this business?', answer: 'The business has grown beyond my operational capacity. It needs someone with experience in scaling hardware and e-commerce businesses.' },
    ],
  },
  {
    id: '17',
    name: 'AcornVest',
    tagline: 'Invest your spare change, automatically.',
    category: 'Fintech',
    description: 'AcornVest is a mobile app that rounds up your everyday purchases to the nearest dollar and invests the spare change into a diversified portfolio of ETFs.',
    problem: 'Many people, especially young adults, feel they don\'t have enough money to start investing or find the process intimidating.',
    solution: 'A "micro-investing" platform that makes it effortless to start investing with small, consistent amounts of money, lowering the barrier to entry.',
    targetAudience: 'Millennials and Gen Z who are new to investing.',
    businessType: 'B2C',
    projectUrl: 'https://acornvest.io',
    twitterUrl: 'https://x.com/acornvest',
    paymentGatewayApiKey: 'pk_test_dummy_acornvest',
    techStack: ['Swift (iOS)', 'Kotlin (Android)', 'Plaid API', 'Apex Clearing (Brokerage)'],
    mrr: 50000,
    mrrVerified: true,
    users: 200000,
    usersVerified: true,
    price: 2500000,
    lifetimeRevenue: 6800000,
    whatYouGet: ['Mobile apps', 'Brokerage integrations', 'Userbase', 'Brand assets'],
    founder: {
      name: 'Nate Thompson',
      bio: 'A financial advisor who wanted to make investing more accessible for the next generation.',
      founderTwitterUrl: 'https://x.com/natethompson'
    },
    qna: [
      { question: 'What is your business model?', answer: 'We charge a simple flat fee of $1 per month for accounts under $5,000 and 0.25% per year for accounts over that amount.' },
      { question: 'What are the main regulatory hurdles?', answer: 'As a financial app, we are subject to FINRA and SEC regulations. We have a compliance framework in place and use a registered broker-dealer (Apex Clearing) to handle the investments.' },
      { question: 'Why are you selling this business?', answer: 'We have been acquired by a major bank, but this specific product line is being divested due to strategic overlap. It\'s a profitable, standalone business ready for a new owner.' },
    ],
  }
];

export const generateStartupListings = async (count: number): Promise<StartupListing[]> => {
  // Simulate network delay to show loading indicators
  await new Promise(resolve => setTimeout(resolve, 500));
  return Promise.resolve(dummyData.slice(0, count));
};

export const generateSponsoredListings = async (count: number): Promise<StartupListing[]> => {
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 500));
  // Return a shuffled slice for variety
  const shuffled = [...dummyData].sort(() => 0.5 - Math.random());
  return Promise.resolve(shuffled.slice(0, count));
};